<a href="https://colab.research.google.com/github/arthurcamargotradingcomdados/tutoriais_publicos/blob/main/Asset_Allocation_Live_02_03_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Asset Allocation - Risk Contribution

desenvolvido por: https://www.linkedin.com/in/arthur-camargo/

Retorno do Portfólio

<img src="https://latex.codecogs.com/svg.image?\LARGE&space;Retorno_{Portfolio}&space;=&space;\sum_{i=1}^{N}w_{i}\cdot&space;r_{i}" title="https://latex.codecogs.com/svg.image?\LARGE Retorno_{Portfolio} = \sum_{i=1}^{N}w_{i}\cdot r_{i}" />

Volatilidade

<img src="https://latex.codecogs.com/svg.image?\LARGE&space;\sigma&space;_{Portfolio}&space;=&space;\sqrt{({w_{a}^{2}\cdot\sigma_{a}^{2})&plus;({w_{b}^{2}\cdot\sigma_{b}^{2})&plus;2\cdot(w_{a}\cdot&space;w_{b}\cdot&space;\rho_{ab}\cdot&space;\sigma_{a}&space;\cdot&space;\sigma_{b})}" title="https://latex.codecogs.com/svg.image?\LARGE \sigma _{Portfolio} = \sqrt{({w_{a}^{2}\cdot\sigma_{a}^{2})+({w_{b}^{2}\cdot\sigma_{b}^{2})+2\cdot(w_{a}\cdot w_{b}\cdot \rho_{ab}\cdot \sigma_{a} \cdot \sigma_{b})}" />

Bibliotecas

In [ ]:
import numpy as np
import pandas as pd

Pesos

In [ ]:
ativos = ['RENDA VARIAVEL', 'RENDA FIXA']

pesos = np.array([0.60,0.40])

pesos = pd.DataFrame(data={'pesos': pesos}, index=ativos)

In [ ]:
pesos

pesos
RENDA VARIAVEL    0.6
RENDA FIXA        0.4

Volatilidade

In [ ]:
riscos = np.array([0.15,0.05])
risco = pd.DataFrame(data={'risco': riscos}, index=ativos)
risco

risco
RENDA VARIAVEL   0.15
RENDA FIXA       0.05

Risco Individual

In [ ]:
risco_individual = (pesos['pesos']**2)*(risco['risco']**2)
risco_individual

RENDA VARIAVEL    0.0081
RENDA FIXA        0.0004
dtype: float64

Correlação

In [ ]:
correlacao = 0.20

In [ ]:
riscos1 = (risco.loc['RENDA FIXA']) * (risco.loc['RENDA VARIAVEL'])

In [ ]:
pesos1 = (pesos.loc['RENDA FIXA']) * (pesos.loc['RENDA VARIAVEL'])

In [ ]:
co_risk = correlacao * riscos1.values * pesos1.values
co_risk

array([0.00036])

Risco da Carteira

In [ ]:
sigma = risco_individual['RENDA FIXA'] + risco_individual['RENDA VARIAVEL'] + 2*(co_risk)

In [ ]:
risco_carteira = np.sqrt(sigma)
risco_carteira

array([0.09602083])

Contribuição Marginal de Risco - Risk Contribution

In [ ]:
cr_renda_variavel = (risco_individual['RENDA VARIAVEL'] + co_risk)/sigma
cr_renda_variavel 

array([0.9175705])

In [ ]:
cr_renda_fixa = (risco_individual['RENDA FIXA'] + co_risk)/sigma
cr_renda_fixa

array([0.0824295])

Função de contribuição marginal de risco


In [ ]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 KB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 KB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 30.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.8/112.8 KB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 9.1 MB/s eta 0:00:00
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting un

In [ ]:
import yfinance as yf

In [ ]:
ativos = ['PETR4.SA', 'VALE3.SA', 'ABEV3.SA', 'WEGE3.SA']
pesos = np.array([0.2,0.3,0.3,0.2])

In [ ]:
df = yf.download(ativos, start='2021-01-01', end='2021-12-31')

[*********************100%***********************]  4 of 4 completed


In [ ]:
retornos = df['Adj Close'].pct_change()
retornos

ABEV3.SA  PETR4.SA  VALE3.SA  WEGE3.SA
Date                                              
2021-01-04       NaN       NaN       NaN       NaN
2021-01-05  0.021318  0.039087  0.016838  0.061377
2021-01-06  0.020240  0.001997  0.032796  0.026515
2021-01-07 -0.004960  0.029900  0.065278  0.041328
2021-01-08  0.029907  0.003871 -0.003127  0.060477
...              ...       ...       ...       ...
2021-12-23  0.010396  0.006037 -0.009635 -0.005940
2021-12-27 -0.001286  0.014825 -0.002527 -0.008963
2021-12-28 -0.000644  0.001044 -0.024066  0.003618
2021-12-29 -0.004510 -0.008339  0.002596 -0.016521
2021-12-30 -0.001942 -0.003154  0.009191  0.007330

[247 rows x 4 columns]

In [ ]:
cov = retornos.cov()

In [ ]:
cov

ABEV3.SA  PETR4.SA  VALE3.SA  WEGE3.SA
ABEV3.SA  0.000357  0.000180  0.000039  0.000111
PETR4.SA  0.000180  0.000763  0.000184  0.000152
VALE3.SA  0.000039  0.000184  0.000491  0.000060
WEGE3.SA  0.000111  0.000152  0.000060  0.000477

Bônus - Função calcula contribuição marginal de risco

In [ ]:
def risk_contribution(pesos, cov_matrix):
    
    portfolio_var = np.dot(pesos.T, np.dot(cov_matrix, pesos))
    asset_contribution = np.dot(cov_matrix, pesos) / portfolio_var
    
    return asset_contribution * pesos

In [ ]:
risk_contribution(pesos,cov)

array([0.13270904, 0.43836109, 0.27800287, 0.150927  ])